### PR TITLE
Bugfix in AI Attack, Replaced tabs with spaces in some files

### PR DESCRIPTION
**Pull request by ChrSacher**

### CODE REVIEW

**Comment by Drofseh** [comment]
I was told to use tabs instead of spaces by @BlackHawkPL

**Comment by ChrSacher** [comment]
I actually don't remember what was the norm for it. But these were the only files where my IDE found tabs instead of spaces so might be my mistake.

**Comment by ChrSacher** [comment]
I also think its not an issue because github changed them to tabs anyway and pretty much all modern IDEs convert them automatically.

**Comment by Drofseh** [comment]
I definitely prefer spaces myself, I'm just a little confused.

**Comment by ChrSacher** [comment]
We never had any "real" coding guidelines. You will notice that everything is different in some way if you look through all the files.

**Pull request merged**
